openapi: 3.0.1
info:
  title: Tempest Proof of Concept  description: |
    <a>TEMPEST HTML INJECTION</a>

  version: '1.0'
paths:
  "/path/malformed/by/afine":
    post:
      tags:
      - afine
      parameters:
      - name: afine
