---
openapi: 3.0.1
info:
  title: Afineeee Api<script>alert(document.cookie)</script>
  version: '1.0'
paths:
  "/path/malformed/by/afine":
    post:
      tags:
      - afine
      parameters:
      - name: afine
